import React, { useState, useEffect } from 'react';
import '../css/style11.css'; // Importing CSS for the supplier management table
import axios from 'axios';
import SlideBar from '../components/Slidebar';
import jsPDF from 'jspdf';
import 'jspdf-autotable'; // Importing autoTable for table generation
import { useNavigate } from 'react-router-dom'; // Importing useNavigate
import logo from '../ES lo.png'; // Import your logo image here

const SupplierManagement = () => {
  const [suppliers, setSuppliers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');

  const navigate = useNavigate();

  // Fetch suppliers from the backend
  useEffect(() => {
    axios.get('http://localhost:8070/suplier/')
      .then((response) => {
        setSuppliers(response.data);
        setLoading(false);
      })
      .catch((error) => {
        console.error("Error fetching suppliers:", error);
        setLoading(false);
      });
  }, []);

  // Handle delete request for suppliers
  const handleDelete = (id) => {
    axios.delete(`http://localhost:8070/suplier/delete/${id}`)
      .then(() => {
        setSuppliers(suppliers.filter(supplier => supplier._id !== id));
      })
      .catch((error) => {
        console.error(`Error deleting supplier with id ${id}:`, error);
      });
  };

  // Filter suppliers based on search input
  const filteredSuppliers = suppliers.filter((supplier) => 
    supplier.itemName.toLowerCase().includes(searchTerm.toLowerCase()) || 
    supplier.itemCode.toLowerCase().includes(searchTerm.toLowerCase())
  );

  // Generate PDF of the supplier table
  const downloadPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(18);

    // Add logo
    doc.addImage(logo, 'PNG', 14, 20, 20, 20); // Adjust the position and size as needed

    // Add title
    doc.setFontSize(17);
    doc.text('WELCOME TO!', 40, 27);
    doc.setFontSize(24);
    doc.text('ES CUSTOMS PVT(LTD)', 40, 38);
    doc.setFontSize(20);
    doc.text('Supplier Management Report', 14, 50);

    // Add current date and time
    const date = new Date();
    doc.setFontSize(12);
    doc.text(`Generated on: ${date.toLocaleString()}`, 14, 60); // Format the date and time

    // Add contact information (aligned to the right side)
    const contactInfo = `Contact: +94 77 726 0247\nEmail: info@ecustoms39@gmail.com\nAddress: 21 Main Street, Jaela, Sri Lanka`;
    doc.setFontSize(12);
    doc.text(contactInfo, 195, 50, { align: 'right' });

    const tableColumn = ["Item Name", "Item Code", "Item Fee", "Description", "Quantity"];
    const tableRows = [];

    filteredSuppliers.forEach(supplier => {
      const supplierData = [
        supplier.itemName,
        supplier.itemCode,
        supplier.itemFee,
        supplier.itemDescription,
        supplier.availableQty,
      ];
      tableRows.push(supplierData);
    });

    // Generate colorful table using autoTable
    doc.autoTable({
      startY: 70, // Adjusted position for the table
      head: [tableColumn],
      body: tableRows,
      theme: 'grid', // Theme for colorful table
      headStyles: { fillColor: [71, 201, 255] }, // Table header color
      alternateRowStyles: { fillColor: [239, 239, 239] }, // Alternating row colors
      styles: { fontSize: 10, cellPadding: 3 }, // Style options
    });

    // Add footer with centered text
    doc.setFontSize(10);
    const pageHeight = doc.internal.pageSize.height; // Get page height
    doc.text('Generated by ES Customs System', 105, pageHeight - 10, { align: 'center' }); // Footer content

    doc.save('Supplier_Management_Report.pdf');
  };

  if (loading) {
    return <p>Loading suppliers...</p>;
  }

  return (
    <div>
      <SlideBar />
      <div className="supplier-management">
        <h1>Supplier <span>Management</span></h1>

        {/* Search bar */}
        <form className="search">
          <button className="search__button" type="button"></button>
          <input 
            type="text" 
            className="search__input" 
            placeholder="Search Item Name or Item Code"  
            onChange={(e) => setSearchTerm(e.target.value)}
          />
        </form>

        {/* Supplier table */}
        <table>
          <thead>
            <tr>
              <th>Item Name</th>
              <th>Item Code</th>
              <th>Item Fee</th>
              <th>Description</th>
              <th>Quantity</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {filteredSuppliers.map((supplier) => (
              <tr key={supplier._id}>
                <td>{supplier.itemName}</td>
                <td>{supplier.itemCode}</td>
                <td>{supplier.itemFee}</td>
                <td>{supplier.itemDescription}</td>
                <td>{supplier.availableQty}</td>
                <td>
                  <button onClick={() => handleDelete(supplier._id)} className="btn-delete">Delete</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* PDF Download button */}
        <button onClick={downloadPDF} className="btn-download-pdf">
          Download PDF
        </button>

        <div className="done-jobs-container">
          <button className="cta" onClick={() => navigate("/Suplier")}>
            <span className="hover-underline-animation">Supply Items </span>
            <svg
              id="arrow-horizontal"
              xmlns="http://www.w3.org/2000/svg"
              width="30"
              height="10"
              viewBox="0 0 46 16"
              fill="white"
            >
              <path
                id="Path_10"
                data-name="Path 10"
                d="M8,0,6.545,1.455l5.506,5.506H-30V9.039H12.052L6.545,14.545,8,16l8-8Z"
                transform="translate(30)"
              />
            </svg>
          </button>
        </div>
      </div>
    </div>
  );
};

export default SupplierManagement;
